name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    env:
      MIX_ENV: test
    strategy:
      matrix:
        include:
          - elixir: "1.13"
            otp: "24.3"
          - elixir: "1.14"
            otp: "25.3"
          - elixir: "1.15"
            otp: "26.0"
          - elixir: "1.16"
            otp: "26.2"
          - elixir: "1.16"
            otp: "27.0-rc3"
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: mix deps.get
      - name: Check compile warnings
        run: mix compile --warnings-as-errors
      - name: Check format
        run: mix format --check-formatted
      - name: Unit tests
        run: mix test.unit
      - name: Property-based tests
        run: PROP_TEST_RUNTIME=30000 mix test.prop
